-- generated by scripts/build_raw.py: tiles of map "0-1458" ("col_row" = layers present:
-- f = fill, h = hatch, s = shade, t = terrain, w = water, r = roads).
-- Tiles on a zone border are split into one part per zone: "col_row_z<zone>".
RunewayTiles = RunewayTiles or {}
RunewayTiles["0-1458"] = {
    ["30_28"] = "fhstw",
    ["30_29"] = "fhst",
    ["31_28"] = "fhstw",
    ["31_29"] = "fhstw",
    ["31_30"] = "h",
    ["32_28"] = "h",
    ["32_29"] = "h",
}
-- Zones: names (index = zone number), zone per tile key, and per border tile the zone of each of its
-- 16 x 16 chunks (row by row from north, columns from west; one character per chunk: 123456789ABC...)
RunewayZones = RunewayZones or {}
RunewayZones["0-1458"] = {
    names = { "Undercity" },
    tile = {
        ["30_28"] = 1,
        ["30_29"] = 1,
        ["31_28"] = 1,
        ["31_29"] = 1,
        ["31_30"] = 1,
        ["32_28"] = 1,
        ["32_29"] = 1,
    },
    chunks = {
    },
}
-- Surface subzones (AreaTable IDs): there the addon keeps the map's own (surface) tiles
RunewayZones["0-1458"].surface = { 153 }
