# Writes Runeway/Locales/enUS.lua and deDE.lua from the text list Runeway_Strings.md (the agreed
# English and German texts). Other languages are kept as their own files in Runeway/Locales/.
#   python scripts/make_locales.py
import os
import re

ROOT = os.path.join(os.path.dirname(__file__), '..')
SRC = os.path.join(ROOT, 'Runeway_Strings.md')
OUT = os.path.join(ROOT, 'Runeway', 'Locales')
PIPE = '\0'


def rows():
    """(key, english, german) for every table row that starts with a `KEY`; the last two columns are the
    texts. A German cell in brackets is a note (the text stays English)."""
    for line in open(SRC, encoding='utf8'):
        m = re.match(r'\|\s*`([A-Z0-9_]+)`\s*\|', line)
        if not m:
            continue
        cells = [c.strip().replace(PIPE, '|') for c in line.replace('\\|', PIPE).strip().strip('|').split('|')]
        en, de = cells[-2], cells[-1]
        yield m[1], en, en if de.startswith('(') else de


def lua(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def write(name, header, pairs):
    with open(os.path.join(OUT, name), 'w', encoding='utf8', newline='\n') as fh:
        fh.write(header)
        for key, text in pairs:
            fh.write(f'L.{key} = {lua(text)}\n')


os.makedirs(OUT, exist_ok=True)
data = list(rows())
write('enUS.lua', '''-- generated by scripts/make_locales.py from Runeway_Strings.md: English, the base for all languages.
-- Other locale files only override keys; a key missing there shows the English text.
local ADDON, ns = ...
local L = {}
ns.L = L
''', [(k, en) for k, en, _ in data])
write('deDE.lua', '''-- generated by scripts/make_locales.py from Runeway_Strings.md
if GetLocale() ~= "deDE" then return end
local ADDON, ns = ...
local L = ns.L
''', [(k, de) for k, _, de in data])
print(f'{len(data)} texts -> Runeway/Locales/enUS.lua, deDE.lua')
